text = "GTGGTACGGGATACGTCCATAAGTTGTGGTACGGGATACGTGTGGTACGGCCATAAGTTCCATAAGTTTGGGCGGCCATAAGTTCCATAAGTTCCATAAGTTCATACTATGTGGTACGGTGGGCGGGTGGTACGGCATACTATCCATAAGTTCATACTATGTGGTACGGTGGGCGGGTGGTACGGCCATAAGTTGTGGTACGGGATACGTTGGGCGGCATACTATCATACTATGATACGTGTGGTACGGCCATAAGTTGTGGTACGGGTGGTACGGGTGGTACGGGTGGTACGGCATACTATGATACGTCCATAAGTTTGGGCGGGATACGTGTGGTACGGGTGGTACGGGTGGTACGGGATACGTTGGGCGGTGGGCGGTGGGCGGTGGGCGGGATACGTCCATAAGTTGTGGTACGGCATACTATGATACGTGATACGTGATACGTCCATAAGTTGATACGTGATACGTCCATAAGTTCCATAAGTTGTGGTACGGCCATAAGTTGATACGTTGGGCGGGATACGTTGGGCGGGTGGTACGGTGGGCGGGTGGTACGGCCATAAGTTGATACGTGTGGTACGGCCATAAGTTGATACGTTGGGCGGTGGGCGGCCATAAGTTCCATAAGTTCCATAAGTTGTGGTACGGTGGGCGGGTGGTACGGGATACGTCCATAAGTTTGGGCGGCATACTATTGGGCGGCATACTATCATACTATGTGGTACGGCATACTATTGGGCGGGATACGTCCATAAGTTGATACGTTGGGCGGCATACTATGTGGTACGGTGGGCGGCATACTATGTGGTACGGGATACGTTGGGCGGGATACGTGTGGTACGGGATACGT"
k = 11


def frequentWords(text, k):
    FrequentPatterns = []
    count = []
    for i in range(len(text)-k+1):
        pattern = text[i:i+k]
        count.append(patterncount(text, pattern))
    maxcount = max(count)
    for i in range(len(text)-k+1):
        if count[i] == maxcount:
            FrequentPatterns.append(text[i:i+k])    
    return set(FrequentPatterns)
    
def patterncount(text, pattern):
    count = 0
    i = 0
    end = len(text) - len(pattern)
    for i in range(end+1):
        if text[i:i+len(pattern)] == pattern:
            count +=1
        i +=1
    return count
    

print frequentWords(text, k)



